### ISSUE TITLE
Error with Hardhat version compatibility on Node.js 20.11.0

### ISSUE THREAD

**Issue by eminmtas** [LayerZero-Labs/mainnet-testnet-bridge#29]
I encountered an error while installing Hardhat via Yarn, indicating incompatibility with Node.js version 20.11.0. Subsequently, I resolved the issue by updating Hardhat using the `npm update hardhat` command.

### Screenshot:
![image](https://github.com/LayerZero-Labs/mainnet-testnet-bridge/assets/44838743/b6f8afa8-c4fe-4b53-b000-b623a5086432)

### Details:
Previously, the project was unable to run on Node.js version 20.11.0 due to an incompatibility with Hardhat version 2.12.2. However, after updating Hardhat, the issue was resolved, and the project was confirmed to be functioning properly.

### Steps Taken:

1. Node.js version was set to 20.11.0.
2. Hardhat version was set to 2.12.2, resulting in an incompatibility error during installation.
3. Hardhat was updated using the `npm update hardhat` command.
4. The issue was resolved, and the project returned to normal functionality.

**I will make a PR and refer this issue.**

**Comment by DanL0** [comment]
It seems Hardhat added support for node v20 in 2.17.0 (https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-core/CHANGELOG.md)

**Comment by eminmtas** [comment]
thanks for the help @DanL0 🙏
